brewcollector/brewcollector/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

brewcollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('brews/', views.brews_index, name='index'),
    path('brews/<int:brew_id>/', views.brews_detail, name='detail'),
    path('brews/create/', views.BrewCreate.as_view(), name='brews_create'),
    #path('brews/new/', views.brews_new),
    path('brews_submit/', views.brews_create),
    path('brews/<int:brew_id>/delete/', views.brews_delete),
    path('brews/<int:brew_id>/edit/', views.brews_edit), 
    path('brews/<int:brew_id>/submit_update_form/', views.brews_update),
    path('brews/<int:brew_id>/add_location/', views.add_location, name='add_location'),
    # associate a ingredient with a brew (M:M)
    path('brews/<int:brew_id>/assoc_ingredient/<int:ingredient_id>/', views.assoc_ing, name='assoc_ing'),
    # unassoc
    path('brews/<int:brew_id>/unassoc_ingredient/<int:ingredient_id>/', views.unassoc_ing, name='unassoc_ing'),
    path('accounts/signup/', views.signup, name='signup'),
]

brewcollector/main_app/models.py
from django.db import models
from django.db.models.fields import IntegerField
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User

LOCATIONS = (
    ('N', 'North Vancouver BCL'),
    ('E', 'East Vancouver BCL'),
    ('S', 'South Vancouver BCL'),
    ('W', 'West Vancouver BCL')
)

class Ingredient(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('ingredients_detail', kwargs={'pk': self.id})    

# Create your models here.
class Brew(models.Model):
    name = models.CharField(max_length=100)
    beerType = models.CharField(max_length=100)
    brewery = models.CharField(max_length=100)
    ibu = IntegerField()
    alcoholPercent = IntegerField()
    price = IntegerField()
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    ingredients = models.ManyToManyField(Ingredient)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'brew_id': self.id})
    
    def stocked(self):
        return self.location_set.stock >= 20

class Locations(models.Model):
    stock = models.IntegerField('stock',default=1)
    date = models.DateField('best before date')
    location = models.CharField(max_length=1,choices=LOCATIONS,default=LOCATIONS[0][0])
    brew = models.ForeignKey(Brew, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.get_location_diplay()} on {self.date}"

brewcollector/main_app/forms.py
from django.forms import ModelForm
from .models import Locations

class LocationsForm(ModelForm):
  class Meta:
    model = Locations
    fields = ['stock', 'date', 'location']

brewcollector/main_app/views.py
from django.shortcuts import redirect, render
from .models import Brew, Ingredient,Locations
from .forms import LocationsForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

from django.http import HttpResponse

# Define the home view
def home(request):
  return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def brews_index(request):
    #brews = Brew.objects.all()
    brews = Brew.objects.filter(user=request.user)
    return render(request, 'brews/index.html', {'brews': brews})

@login_required
def brews_detail(request, brew_id):
    brew = Brew.objects.get(id=brew_id)
    return render(request, 'brews/detail.html', {'brew': brew})


def brews_new(request):
    return render(request,'brews/new.html', {})

#old brews create
@login_required
def brews_create(request):
    brew = Brew.objects.create(
        name = request.POST['name'],
        beerType = request.POST['beerType'],
        brewery = request.POST['brewery'],
        ibu = request.POST['ibu'],
        alcoholPercent = request.POST['alcoholPercent'],
        price = request.POST['price']
        #user = request.user this is how we would do it with not createview
    )

    return redirect(f'/brews/{brew.id}')

class BrewCreate(LoginRequiredMixin,CreateView):
  model = Brew
  fields = ['name', 'beerType', 'brewery', 'ibu','alcoholPercent','price']
  
  def form_valid(self, form):
    form.instance.user = self.request.user  
    return super().form_valid(form)

@login_required
def brews_delete(request, brew_id):
    brew = Brew.objects.get(id=brew_id)
    brew.delete()
    return redirect('/brews')

@login_required
def brews_edit(request, brew_id):
    brew = Brew.objects.get(id=brew_id)
    return render(request, 'brews/edit.html', {'brew':brew})

@login_required
def brews_update(request, brew_id):
    brew = Brew.objects.get(id=brew_id)
    brew.name = request.POST['name']
    brew.beerType = request.POST['beerType']
    brew.brewery = request.POST['brewery']
    brew.ibu = request.POST['ibu']
    brew.alcoholPercent = request.POST['alcoholPercent']
    brew.price = request.POST['price']
    brew.save()
    return redirect(f'/brews/{brew.id}')

@login_required
def brews_detail(request, brew_id):
    brew = Brew.objects.get(id=brew_id)
    location_form = LocationsForm()
    locations = Locations.objects.all()
    count = 0
    for location in locations:
        count+=location.stock
    
    ingredients_brew_doesnt_have = Ingredient.objects.exclude(id__in = brew.ingredients.all().values_list('id'))
    return render(request, 'brews/detail.html', {
        'brew': brew, 'location_form': location_form, 'count': count, 'ingredients':ingredients_brew_doesnt_have
    })

@login_required
def add_location(request, brew_id):
    form = LocationsForm(request.POST)
    if form.is_valid():
        new_location = form.save(commit=False)
        new_location.brew_id = brew_id
        new_location.save()
    return redirect('detail', brew_id=brew_id)

@login_required
def assoc_ing(request, brew_id, ingredient_id):
  # Note that you can pass a toy's id instead of the whole object
  Brew.objects.get(id=brew_id).ingredients.add(ingredient_id)
  return redirect('detail', brew_id=brew_id)

@login_required
def unassoc_ing(request, brew_id, ingredient_id):
  # Note that you can pass a toy's id instead of the whole object
  Brew.objects.get(id=brew_id).ingredients.remove(ingredient_id)
  return redirect('detail', brew_id=brew_id)

def signup(request):
  error_message = ''
  if request.method == 'POST':
    # This is how to create a 'user' form object
    # that includes the data from the browser
    form = UserCreationForm(request.POST)
    if form.is_valid():
      # This will add the user to the database
      user = form.save()
      # This is how we log a user in via code
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  # A bad POST or a GET request, so render signup.html with an empty form
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

brewcollector/main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Brew Collector</h1>
<hr />
<p>Hire the Brew Collector!</p>

{% endblock %}

brewcollector/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Brew Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;BrewCollector</a></li>
        </ul>
        <ul class="right">
          <li><a href="/about">About</a></li>
          {% if user.is_authenticated %}
          <li><a href="/brews/create">Add a Brew</a></li>
          <li><a href="/brews">View All My Brews</a></li>
          <li><a href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li><a href="{% url 'signup' %}">Sign Up</a></li>
          <li><a href="{% url 'login' %}">Log In</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2019 Brew Collector &nbsp;</div>
  </footer>
</body>
</html>

brewcollector/main_app/templates/brews/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Brew Details</h1>

  <div class="card">
    <div class="card-content">
      <span class="card-title">{{ brew.name }}</span>
      Brewery: {{ brew.brewery }}
      <br>
      Beer type: {{brew.beerType}}
      <br>
      Beer IBU: {{brew.ibu}}
      <br>
      Alcohol percent: {{brew.alcoholPercent}}
      <br>
      Price: {{brew.price}}
    </div>
  </div>
  <div class="col s6">
    <table class="striped">
      <thead>
        <tr><th>Stock</th><th>Best before date</th><th>Location</th></tr>
      </thead>
      <tbody>
        {% for locations in brew.locations_set.all %}
          <tr>
            <td>{{locations.stock}}</td>
            <td>{{locations.date}}</td>
            <td>{{locations.get_location_display}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>

    {% if count %}
      <div class="card-panel teal-text center-align">stocked</div> 
    {% else %}
      <div class="card-panel teal-text center-align">not stocked</div> 
    {% endif %}
    
    <form action="{% url 'add_location' brew.id %}" method='post'>
      {% csrf_token %}
      {{ location_form.as_p }}
      <input type="submit" class="btn" value="Add Stock">
    </form>
  </div>
  <div class="row">
    <div class="col s6">
      <h3>{{ brew.name }}'s Ingredients</h3>
      {% if brew.ingredients.count %}
        {% for ingredient in brew.ingredients.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                {{ ingredient.name }}
              </span>
            </div>
            <div class='card-action'>
              <form action="{% url 'unassoc_ing' brew.id ingredient.id %}" method="post">
                {% csrf_token %}
              <button type="submit" class="btn">Remove</button>
            </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>No Ingredients :(</h5>
      {% endif %}
    </div>
    <div class="col s6">
      <h3>Available Ingredients</h3>
      {% if ingredients.count %}
        {% for ingredient in ingredients.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
              {{ ingredient.name }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url 'assoc_ing' brew.id ingredient.id %}" method="post">
                  {% csrf_token %}
                <button type="submit" class="btn">Add</button>
              </form>
            </div>
          </div>
        {% endfor %}
      {% else %}
        <h5>{{brew.name}} Already Has All Ingredients Available</h5>
      {% endif %}
    </div>  
  <script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  var selectEl = document.getElementById('id_location');
  M.FormSelect.init(selectEl);
  </script>
{% endblock %}

brewcollector/main_app/templates/brews/edit.html
{% extends 'base.html' %}
{% block content %}
<form method="POST" action="/brews/{{ brew.id }}/submit_update_form/">
    {% csrf_token %}

    Name: <input name="name" value='{{brew.name}}'>
    Beer Type: <input name="beerType" value='{{brew.beerType}}'>
    Brewery: <input name="brewery" value='{{brew.brewery}}'>
    IBU: <input name="ibu" value='{{brew.ibu}}'>
    Alcohol Percent: <input name="alcoholPercent" value='{{brew.alcoholPercent}}'>
    Price: <input name="price" value='{{brew.price}}'>
    
    <button type="submit">Update</button>
</form>
{% endblock %}

brewcollector/main_app/templates/brews/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Brew List</h1>

{% for brew in brews %}
  <div class="card">
    <a href="{% url 'detail' brew.id %}">
      <div class="card-content">
      <span class="card-title">{{ brew.name }}</span>
      Brewery: {{ brew.brewery }}
      <br>
      Beer type: {{brew.beerType}}
      <br>
      Beer IBU: {{brew.ibu}}
      <br>
      Alcohol percent: {{brew.alcoholPercent}}
      <br>
      Price: {{brew.price}}
      <br>
    </div>
    </a>
    <div class='card-action'>
      <a href="/brews/{{ brew.id }}/edit/">Edit</a> 
      <a href="/brews/{{ brew.id }}/delete/">Delete</a>
    </div>
  </div>
{% endfor %}
<a href="/brews/new">
  <div class='card'>
    <div class='card-content'>
      Create new Brew
    </div>
  </div>
</a>
{% endblock %}

brewcollector/main_app/templates/brews/new.html
{% extends 'base.html' %}
{% block content %}

<form method="POST" action="/brews_submit/">
    {% csrf_token %}
    Name: <input name="name">
    Beer Type: <input name="beerType">
    Brewery: <input name="brewery">
    IBU: <input name="ibu">
    Alcohol Percent: <input name="alcoholPercent">
    Price: <input name="price">
    <button type="submit">Add</button>
</form>

{% endblock %}

brewcollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>its brewtime</h1>


{% endblock %}

brewcollector/main_app/templates/main_app/brew_form.html
{% extends 'base.html' %}
{% block content %}

<form method="POST" action="/brews_submit/">
    {% csrf_token %}
    Name: <input name="name">
    Beer Type: <input name="beerType">
    Brewery: <input name="brewery">
    IBU: <input name="ibu">
    Alcohol Percent: <input name="alcoholPercent">
    Price: <input name="price">
    <button type="submit">Add</button>
</form>

{% endblock %}